title: Mr
author: Jermaine Lecky
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Discussions on my favorite scifi movies, tv shows, and video games.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
